# Generated by Django 4.2.20 on 2025-04-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('google', 'Google Calendar Click'), ('ics', 'ICS Download Click'), ('outlook', 'Outlook Calendar Click')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='events.event')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['event', 'clicked_at'], name='events_widg_event_i_fb261a_idx'), models.Index(fields=['event', 'interaction_type'], name='events_widg_event_i_8b32b9_idx')],
            },
        ),
    ]
