# Generated by Django 4.2.20 on 2025-04-26 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_widgetinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
